# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_c_pb2 as service__c__pb2


class ServiceCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponse = channel.unary_unary(
                '/service_c.ServiceC/GetResponse',
                request_serializer=service__c__pb2.RequestC.SerializeToString,
                response_deserializer=service__c__pb2.ResponseC.FromString,
                )


class ServiceCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=service__c__pb2.RequestC.FromString,
                    response_serializer=service__c__pb2.ResponseC.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service_c.ServiceC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service_c.ServiceC/GetResponse',
            service__c__pb2.RequestC.SerializeToString,
            service__c__pb2.ResponseC.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
