# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_c.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fservice_c.proto\x12\tservice_c\"\x1b\n\x08RequestC\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tResponseC\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\x08ServiceC\x12\x38\n\x0bGetResponse\x12\x13.service_c.RequestC\x1a\x14.service_c.ResponseCb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_c_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTC']._serialized_start=30
  _globals['_REQUESTC']._serialized_end=57
  _globals['_RESPONSEC']._serialized_start=59
  _globals['_RESPONSEC']._serialized_end=87
  _globals['_SERVICEC']._serialized_start=89
  _globals['_SERVICEC']._serialized_end=157
# @@protoc_insertion_point(module_scope)
